from utils import run_bespokefit_all_smiles

# List your config files here or use a wildcard/glob to find them
CONFIGS, = glob_wildcards("configs/{config}.yaml")

rule all:
    input:
        expand("results/{config}.benchmark.txt", config=CONFIGS)

rule get_torsionnet_500_input:
    output:
        "torsionnet_500/input/smiles.csv",
        "torsionnet_500/input/TNet500_minimal_dataset.json"
    shell:
        """
        mkdir -p torsionnet_500/input
        cd torsionnet_500/input
        curl https://zenodo.org/records/11385284/files/TNet500_minimal.zip?download=1 -o TNet500_minimal.zip
        unzip TNet500_minimal.zip
        rm TNet500_minimal.zip
        rm -r __MACOSX
        python ../scripts/create_dataset.py
        python ../scripts/extract_smiles.py
        cd ../..
        """

rule run_fits:
    input:
        config_file="configs/{config}.yaml",
        smiles_file="{benchmark_dir}/input/smiles.csv"
    output:
        force_field="{benchmark_dir}/output/{config}/combined_forcefield.offxml"
    run:
        run_bespokefit_all_smiles(input.config_file,
                                  input.smiles_file,
                                  wildcards.benchmark_dir,
                                  wildcards.config)

rule analyse_torsionnet_500:
    input:
        # config_file="configs/{config}.yaml",
        force_field="torsionnet_500/output/{config}/combined_forcefield.offxml",
        input_data="torsionnet_500/input/TNet500_minimal_dataset.json"
    output:
        dummy_output="torsionnet_500/analysis/{config}_dummy_output.txt"
    shell:
        """
        mkdir -p torsionnet_500/analysis
        cd torsionnet_500/analysis
        yammbs_analyse_torsions --base-force-fields openff-2.2.1 \
        --extra-force-fields ../output/espaloma03/combined_forcefield.offxml \
        --extra-force-fields ../output/aimnet2/combined_forcefield.offxml \
        --extra-force-fields ../output/aimnet2_metad/combined_forcefield.offxml \
        --extra-force-fields ../output/egret1_metad/combined_forcefield.offxml \
        --extra-force-fields ../output/{wildcards.config}/combined_forcefield.offxml \
        --qcarchive-torsion-data ../input/TNet500_minimal_dataset.json &&
        touch {output.dummy_output}
        cd ../..
        """
