name: bespokefit_smee

channels:
  - conda-forge
  - bioconda

dependencies:
    # Base dependencies
    - python>=3.11
    - pyyaml
    - smee
    - descent
    - datasets
    - jupyter
    - nglview
    - smirnoff-plugins >=0.0.4
    - openmm>=8.2
    - openff-toolkit
    - openff-units
    - openff-interchange
    - openmm-ml
    - tensorboardX
    - tensorboard
    - versioneer
    - pytorch-gpu
    - pydantic>=2
    - pydantic-settings
    - loguru
    - qcelemental
    - openff-qcsubmit

    # Workflow
    - snakemake
